SET SQLBLANKLINES ON;

INSERT INTO med_department
(DEPARTMENT_ID, ESTABLISHMENT_ID,  HOSPITAL_ID, CASE_NUMBER, NUMBER_OF_CHAMBERS, NUMBER_OF_BEDS)
VALUES
(1, 11, 101, 1, 80, 100);

INSERT INTO med_department
(DEPARTMENT_ID, ESTABLISHMENT_ID,  HOSPITAL_ID, CASE_NUMBER, NUMBER_OF_CHAMBERS, NUMBER_OF_BEDS)
VALUES
(2, 12, 102, 1, 50, 80);

INSERT INTO med_department
(DEPARTMENT_ID, ESTABLISHMENT_ID,  HOSPITAL_ID, CASE_NUMBER, NUMBER_OF_CHAMBERS, NUMBER_OF_BEDS)
VALUES
(3, 13, 103, 1, 200, 300);