SET SQLBLANKLINES ON;

INSERT INTO hospitals
(HOSPITAL_ID, ESTABLISHMENT_ID,  NUMBER_OF_CHAMBERS, NUMBER_OF_BEDS)
VALUES
(101, 11, 80, 100);

INSERT INTO hospitals
(HOSPITAL_ID, ESTABLISHMENT_ID,  NUMBER_OF_CHAMBERS, NUMBER_OF_BEDS)
VALUES
(102, 12, 50, 80);

INSERT INTO hospitals
(HOSPITAL_ID, ESTABLISHMENT_ID,  NUMBER_OF_CHAMBERS, NUMBER_OF_BEDS)
VALUES
(103, 13, 200, 300);