SET SQLBLANKLINES ON;

INSERT INTO chambers
(CHAMBER_ID, DEPARTMENT_ID,  CHAMBER_NUMBER)
VALUES
(10, 1, 1);

INSERT INTO chambers
(CHAMBER_ID, DEPARTMENT_ID,  CHAMBER_NUMBER)
VALUES
(11, 2, 2);

INSERT INTO chambers
(CHAMBER_ID, DEPARTMENT_ID,  CHAMBER_NUMBER)
VALUES
(12, 3, 3);