SET SQLBLANKLINES ON;

INSERT INTO doctor_to_department
(ID, DEPARTMENT_ID,  EMPLOYEE_ID)
VALUES
(1, 1, 10001);

INSERT INTO doctor_to_department
(ID, DEPARTMENT_ID,  EMPLOYEE_ID)
VALUES
(2, 2, 10002);

INSERT INTO doctor_to_department
(ID, DEPARTMENT_ID,  EMPLOYEE_ID)
VALUES
(3, 3, 10003);