--1
CREATE TABLE DEPARTMENT
(ID NUMBER(7)
CONSTRAINT department_ID_pk PRIMARY KEY,
NAME CHAR(25));

CREATE TABLE EMPLOYEE
(ID  NUMBER(7)
CONSTRAINT employee_ID_pk PRIMARY KEY,
LAST_NAME CHAR(25),
FIRST_NAME CHAR(25),
DEPT_ID NUMBER(7)
CONSTRAINT employee_DEPT_ID_fk REFERENCES DEPARTMENT(ID)
CONSTRAINT employee_DEPT_ID_nn NOT NULL);

DESCRIBE DEPARTMENT

DESCRIBE EMPLOYEE;
--2
SELECT *
FROM DICTIONARY
WHERE LOWER(COMMENTS) LIKE '%table%';
--3
SELECT *
FROM USER_OBJECTS
WHERE OBJECT_TYPE = 'TABLE' AND (OBJECT_NAME = 'DEPARTMENT' OR OBJECT_NAME = 'EMPLOYEE');
--4
SPOOL C:\Games\sqlplus\Lab6Zad4.sql
SELECT constraint_name, constraint_type,
search_condition, r_constraint_name
FROM user_constraints
WHERE table_name = 'DEPARTMENT' OR table_name = 'EMPLOYEE';
SPOOL OFF
--5
CREATE TABLE WORKER AS SELECT *
FROM EMPLOYEE;

DESCRIBE WORKER

SPOOL C:\Games\sqlplus\Lab6Zad5.sql
SELECT constraint_name, constraint_type,
search_condition, r_constraint_name
FROM user_constraints
WHERE table_name = 'WORKER';
SPOOL OFF
--6
ALTER TABLE WORKER ADD CONSTRAINT worker_id_pk PRIMARY KEY (ID);
--7
ALTER TABLE WORKER ADD CONSTRAINT worker_dept_id_fk FOREIGN KEY (DEPT_ID) REFERENCES DEPARTMENT(ID);
--8
SELECT OBJECT_NAME, OBJECT_TYPE
FROM USER_OBJECTS
WHERE OBJECT_NAME = 'DEPARTMENT' OR OBJECT_NAME = 'EMPLOYEE' OR OBJECT_NAME = 'WORKER';
--9
--a
INSERT INTO DEPARTMENT VALUES (37, 'Marketing');
INSERT INTO DEPARTMENT VALUES (54, 'Sales');
INSERT INTO DEPARTMENT VALUES (75, 'Personnel');

SELECT *
FROM DEPARTMENT;
--b
SAVEPOINT "16.07.21";
--c
DELETE FROM DEPARTMENT;

SELECT *
FROM DEPARTMENT;
--d
ROLLBACK TO SAVEPOINT "16.07.21";

SELECT *
FROM DEPARTMENT;
--e
COMMIT;
