-- Задание 1
SELECT C.NAME, E.LAST_NAME, E.FIRST_NAME
FROM S_EMP E RIGHT JOIN S_CUSTOMER C
ON E.ID = C.SALES_REP_ID;

-- Задание 2
SELECT C.NAME, E.ID
FROM S_EMP E LEFT JOIN S_CUSTOMER C
ON E.ID = C.SALES_REP_ID;

-- Задание 3
SELECT R.NAME, C.NAME
FROM S_REGION R FULL JOIN S_CUSTOMER C
ON R.ID = C.REGION_ID; 

-- Задание 4
SELECT EC.LAST_NAME, EC.FIRST_NAME
FROM S_EMP_COPY EC INNER JOIN S_TITLE T
ON EC.TITLE = T.TITLE;

-- Задание 5
SELECT C.NAME, O.ID, COUNT(O.ID)
FROM S_CUSTOMER C INNER JOIN S_ORD O
ON O.CUSTOMER_ID = C.ID
WHERE O.TOTAL > 100000
GROUP BY C.NAME, O.ID;

-- Задание 6
SELECT R.ID, R.NAME, D.NAME, COUNT(E.ID)
FROM S_REGION R FULL JOIN S_DEPT D 
ON R.ID = D.REGION_ID
FULL JOIN S_EMP E
ON E.DEPT_ID = D.ID
GROUP BY R.ID, R.NAME, D.NAME;


-- Задание 7
SELECT C.NAME, O.ID, COUNT(O.ID)
FROM S_CUSTOMER C FULL JOIN S_ORD O
ON O.CUSTOMER_ID = C.ID
GROUP BY C.NAME, O.ID;


-- Задание 8
SELECT P.NAME, COUNT(C.ID)
FROM S_CUSTOMER C RIGHT JOIN S_ORD O
ON C.ID = O.CUSTOMER_ID
RIGHT JOIN S_ITEM I
ON I.ORD_ID = O.ID
RIGHT JOIN S_PRODUCT P
ON P.ID = I.PRODUCT_ID
GROUP BY P.NAME;

-- Задание 9
CREATE TABLE Numbers(
  NUMB INT
 );

INSERT INTO Numbers (NUMB) VALUES (1);
INSERT INTO Numbers (NUMB) VALUES (2);
INSERT INTO Numbers (NUMB) VALUES (3);
INSERT INTO Numbers (NUMB) VALUES (4);
INSERT INTO Numbers (NUMB) VALUES (5);
INSERT INTO Numbers (NUMB) VALUES (6);
INSERT INTO Numbers (NUMB) VALUES (7);
INSERT INTO Numbers (NUMB) VALUES (8);
INSERT INTO Numbers (NUMB) VALUES (9);
INSERT INTO Numbers (NUMB) VALUES (10);

SELECT n.NUMB,n1.NUMB,n.NUMB*n1.NUMB AS Multiplication
FROM NUMBERS n CROSS JOIN NUMBERS n1;

DROP TABLE Numbers;




