--1
SELECT last_name "Last Name", first_name "First Name", TO_CHAR(START_DATE,'dd.mm.yyyy') "Start Date", title "Title"
  FROM S_EMP
  WHERE dept_id =
  (SELECT dept_id
    FROM s_emp
    WHERE last_name = 'Magee');

--2
SELECT id, last_name, first_name, USERID
  FROM S_EMP
  WHERE salary >
  (SELECT AVG(salary)
    FROM s_emp);

--3
SELECT last_name, dept_id, title
  FROM S_EMP
  WHERE dept_id IN
  (SELECT id
  FROM S_DEPT
  WHERE REGION_ID = 1 OR REGION_ID = 2);

--4
SELECT last_name, salary
  FROM S_EMP
  WHERE MANAGER_ID =
  (SELECT manager_id
  FROM S_EMP
  WHERE LAST_NAME = 'Ngao');

--5
SELECT id, first_name, last_name
  FROM S_EMP
  WHERE dept_id IN
  (SELECT dept_id
  FROM S_EMP
  WHERE first_name LIKE '%t%')
  AND SALARY > 
  (SELECT AVG(SALARY)
  FROM S_EMP);

--6
SELECT C.ID, C.NAME, C.CREDIT_RATING, E.LAST_NAME
FROM S_CUSTOMER C JOIN S_EMP E ON C.SALES_REP_ID = E.ID
WHERE C.REGION_ID IN
  (SELECT ID 
  FROM S_REGION
  WHERE NAME LIKE 'S.America')
OR C.SALES_REP_ID =
  (SELECT ID
  FROM S_EMP
  WHERE LAST_NAME LIKE 'Nguyen');

--7
SELECT P.NAME, P.SHORT_DESC
FROM S_PRODUCT P JOIN S_ITEM I ON P.ID = I.PRODUCT_ID
WHERE  I.ORD_ID NOT IN
  (SELECT ID 
  FROM S_ORD
  WHERE TO_CHAR(DATE_ORDERED, 'mm.yyyy') = '09.1992');

--8
SELECT NAME, CREDIT_RATING
FROM S_CUSTOMER
WHERE SALES_REP_ID =
  (SELECT ID 
  FROM S_EMP
  WHERE FIRST_NAME LIKE 'Andre'
  AND LAST_NAME LIKE 'Dumas');

--9
SELECT C.NAME, E.LAST_NAME, SUM(O.TOTAL)
FROM S_EMP E JOIN S_CUSTOMER C ON E.ID = C.SALES_REP_ID
JOIN S_ORD O ON C.ID = O.CUSTOMER_ID
WHERE C.REGION_ID IN
  (SELECT ID 
  FROM S_REGION
  WHERE ID = 1 OR ID = 2)
GROUP BY C.NAME, E.LAST_NAME;

--10
SELECT C.NAME, C.ID, COUNT(*)
FROM S_CUSTOMER C JOIN S_ORD O ON C.ID = O.CUSTOMER_ID
GROUP BY O.CUSTOMER_ID, C.NAME, C.ID
HAVING COUNT(*) =
  (SELECT MAX(COUNT(*))
  FROM S_ORD
  GROUP BY CUSTOMER_ID);