--1
CREATE VIEW EMP_VU1
  AS SELECT id, last_name "EMPLOYEE", dept_id
  FROM WORKER_;

SELECT * FROM EMP_VU1;

--2
UPDATE EMP_VU1
SET DEPT_ID = 37
WHERE EMPLOYEE = 'Smith';

SELECT * FROM EMP_VU1;

--3 
CREATE VIEW MNS_VU1
AS SELECT w.ID "emp_ID", d.NAME, w.DEPT_ID
FROM DEPARTMENT d, WORKER w
WHERE d.ID = w.DEPT_ID;

SELECT * FROM MNS_VU1;
SELECT view_name, text
FROM user_views
WHERE view_name = 'MNS_VU';

--4
SELECT NAME, COUNT(*) FROM MNS_VU1
GROUP BY NAME;

--5
CREATE OR REPLACE VIEW EMP_VU1
AS SELECT *
FROM WORKER
WHERE DEPT_ID = 37
WITH CHECK OPTION CONSTRAINT empvu1_ck;

SELECT * FROM EMP_VU1;

--6
SELECT *
FROM EMP_VU1
WHERE LAST_NAME = 'Smith';

--7
CREATE VIEW ORD_VU1
AS SELECT DISTINCT p.ID, p.NAME
FROM S_PRODUCT p, S_ITEM i
WHERE i.PRODUCT_ID = p.ID
AND i.ORD_ID NOT IN
   (
     SELECT ID
     FROM S_ORD
     WHERE TO_CHAR(DATE_ORDERED, 'yyyy') LIKE '1992'
   );

SELECT * FROM ORD_VU1;


--8
CREATE VIEW	CUS_VU1
AS SELECT c.NAME "Customer_NAME", p.NAME "Product_NAME", i.PRICE, i.QUANTITY, i.PRICE * i.QUANTITY "Total cost"
FROM S_CUSTOMER c, S_ORD o, S_ITEM i, S_PRODUCT p
WHERE c.ID = o.CUSTOMER_ID
AND o.ID = i.ORD_ID
AND i.PRODUCT_ID = p.ID
AND c.REGION_ID = 1;

SELECT * FROM CUS_VU1;